### hostname
@hostname = http://localhost:4000/api/v1

### API create a course
POST {{hostname}}/courses
Content-Type: application/json

{
  "name": "test2",
  "teacherCode": "1"
}

### API Find all course
GET {{hostname}}/courses

### API Find a course by id
GET {{hostname}}/courses/2503D5C2-8AFB-45B5-898E-68D419C1C2D2

### API Delete a course by id
DELETE {{hostname}}/courses/2503D5C2-8AFB-45B5-898E-68D419C1C2D2
### API Update a course by id
PUT {{hostname}}/courses/2503D5C2-8AFB-45B5-898E-68D419C1C2D2
Content-Type: application/json

{
  "name": "Java Cơ bản",
  "teacherCode": "1"
}

### API Get lesson by id course
GET {{hostname}}/courses/9F7376E0-14D0-44B7-A96D-02FEF3722291/lessons