### hostname
@hostname = http://localhost:4000/api/v1
@token = {{auth.response.body.$.metadata.accessToken}}

### API SignIn Student
# @name auth
POST {{hostname}}/auth/student/sign-in
Content-Type: application/json

{
  "email": "hieu@gmail.com",
  "password": "123"
}

### API create a question answer
POST {{hostname}}/question-answers
Content-Type: application/json

{
  "idQuestion": "537c959f-f0c3-44b6-8114-8cac49c691d8",
  "answer": "sada",
  "isCorrect": true
}

### API Find a question answer by id
GET {{hostname}}/question-answers/48CBD26F-50BA-488B-AF81-8F10EE54A661

### API Find all question answer
GET {{hostname}}/question-answers