### hostname
@hostname = http://localhost:4000/api/v1

### API create a student question answers
POST {{hostname}}/student-question-answers
Content-Type: application/json

{
  "studentCode": "",
  "idTestQuestion": "",
  "idQuestionAnswer": 
}

### API Find a student question answer by id
GET {{hostname}}/student-question-answers/48CBD26F-50BA-488B-AF81-8F10EE54A661

### API Find all student question answer
GET {{hostname}}/student-question-answers