### hostname
@hostname = http://localhost:4000/api/v1

### API create a student question answers
POST {{hostname}}/student-question-answers
Content-Type: application/json

{
  "studentCode": "",
  "idTestQuestion": "",
  "idQuestionAnswer": 
}