### hostname
@hostname = http://localhost:4000/api/v1

### API create a question answer
POST {{hostname}}/test-questions
Content-Type: application/json

{
  "studentCode": "",
  "idTest": "",
  "idQuestion": 
}